### PR TITLE
Added aa events dvars

### PR DESCRIPTION
**Pull request by Martos**
Added some dvar related on aa events in single player

### CODE REVIEW

**Comment by fedddddd** [comment]
What are these used for exactly?

**Comment by Martos** [comment]
These dvar are used in all Call of Duty titles for tracking stats in single player. These are also present in H2

**Comment by mjkzy** [comment]
i see your h1-stats and h2-stats mod that uses it. are you are adding statistics for SP?

**Comment by Martos** [comment]
Yes, there are a mod for tracking stats in campaign

**Pull request merged**
