### PR TITLE
Copyright text fix

### PR DESCRIPTION
**Pull request by VladWinner**

### CODE REVIEW

**Comment by mjkzy** [comment]
while you're at it, wanna change all of X Labs to H1-mod? :D

**Comment by VladWinner** [comment]
I know it's too simple and small for a commit/PR, but anyway 🤓

**Comment by mjkzy** [comment]
yes, those 3 name + one in auth.cpp

**Comment by VladWinner** [comment]
Btw, is this part (`g78a48f9`) really needed to display in the main menu? It doesn't seem to be changing.
IMG_20220627_025602_304
IMG_20220627_025700_625
Is it supposed to show ID of the last commit on GitHub or something else?

**Comment by mjkzy** [comment]
its the commit of the CI build iirc, i dont really know

**Pull request merged**
