### PR TITLE
Bots don't count as player

### PR DESCRIPTION
**Pull request by DoktorSAS**
Bots don't get considered as player on the serverlist

### CODE REVIEW

**Comment by fedddddd** [comment]
> Bots don't get considered as player on the serverlist

They do actually and that's how it should be, this pr seems to make it do the opposite so I'm confused

**Comment by mjkzy** [comment]
> > Bots don't get considered as player on the serverlist
> 
> 
> 
> They do actually and that's how it should be, this pr seems to make it do the opposite so I'm confused

Broken english, pretty he meant "Bots are now not considered players"

**Comment by DoktorSAS** [comment]
IT: Con questo piccolo cambiamento nella server list vengono mostrati solo i giocatori effettivi e non i bot. `server.clients` contiene sia i giocatori che i bot. Quindi togliendo a `server.clients` i numeri di bot si ottiene il numero di giocatori effettivi.

EN: With this small change in the server list only actual players are shown and not bots. `server.clients` contains both players and bots. So taking away the numbers of bots from server.clients gives the number of actual players

**Comment by diamante0018** [comment]
I can confirm ita to eng translation checks out

**Comment by mjkzy** [comment]
solved in https://github.com/h1-mod/h1-mod/commit/61d66e79989388b8d4f89ee215d2bfad694db9e0

**Pull request closed without merging**
